version: "3"

services:
    php:
        build:
            context: ./
        volumes:
            - ./:/var/www/html

    web:
        image: nginx
        working_dir: /var/www/html/public
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/nginx_template_local.conf:/etc/nginx/conf.d/default.conf

        ports:
          - "80:80"

    db:
        image: mysql:8

        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: ${ALLOW_EMPTY_PASSWORD}
            MYSQL_ROOT_HOST: "%"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"

        volumes:
            - mysqldata:/var/lib/mysql

volumes:
    mysqldata:
